name: 'Code Quality Checks'

permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: '31 7 * * 3'
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
      - labeled
    paths:
      - '**.ts'
      - '**.*js'
      - '**/package*.json'
      - '**/pnpm-lock.yaml'
      - '**/workflows/code-quality-checks.yaml'
      - 'qodana.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql-quality-checks:
    name: CodeQL
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.draft }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['TypeScript', 'JavaScript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yaml

      - name: Setup Project
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm prep

      - name: Build Project
        run: pnpm build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # qodana-quality-checks:
  #   name: Qodana
  #   runs-on: ubuntu-latest
  #   if: |
  #     !github.event.pull_request.draft &&
  #     ((
  #       github.actor == 'dependabot[bot]' &&
  #       contains(github.event.pull_request.title, 'Bump JetBrains/qodana-action')
  #     ) ||
  #     (
  #       github.actor != 'dependabot[bot]'
  #     ))
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Project
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v3
  #       with:
  #         version: latest
  #         run_install: false

  #     - name: Get pnpm store directory
  #       shell: bash
  #       run: |
  #         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

  #     - name: Setup pnpm cache
  #       uses: actions/cache@v4
  #       with:
  #         path: ${{ env.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-

  #     - name: Install dependencies
  #       run: pnpm prep

  #     - name: Build Project
  #       run: npm run build

  #     - name: Qodana Scan
  #       uses: JetBrains/qodana-action@v2023.3.1
  #       with:
  #         pr-mode: false
  #         post-pr-comment: false

  #     - name: Upload Results
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
  #         wait-for-processing: true

  eslint-quality-checks:
    name: Linting
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Project
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm prep

      - name: Build Project
        run: pnpm build

      - name: Package Dedupe Check (pnpm)
        id: packages-check
        run: pnpm lint:packages
        continue-on-error: true

      - name: Auto-fix Dedupe
        if: ${{ steps.packages-check.outcome == 'failure' }}
        run: pnpm dedupe

      - name: Spell Check (cspell)
        id: spell-check
        run: pnpm lint:spelling
        continue-on-error: true

      - name: Lint Check (eslint)
        id: lint-check
        run: pnpm ci:lint
        continue-on-error: true

      - name: Commit Auto-fixable Changes (if failed check)
        if: ${{ github.event_name == 'pull_request' && steps.packages-check.outcome == 'failure' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Dedupe package dependencies
          file_pattern: 'pnpm-lock.yaml'
          commit_user_name: GitHub Actions
          commit_user_email: action@github.com
          commit_author: GitHub Actions <actions@github.com>

      - name: Clean Sarif File
        run: node ./.github/codeql/sarif-cleanup.js

      - name: Upload Linting Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint.sarif
          wait-for-processing: true

      - name: Remove Trigger Label
        uses: actions/github-script@v7
        if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'trigger actions') }}
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.payload.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Trigger Actions'
            })

      - name: Report Failures
        if: ${{ steps.packages-check.outcome == 'failure' ||  steps.spell-check.outcome == 'failure' || steps.lint-check.outcome == 'failure' }}
        run: exit 1
